// GENERATED by scripts/build_assets.py — every photo's size and average tone.
// The tone paints the frame until the image has pixels.
export const PHOTOS = {
  "tea-service": {
    "w": 904,
    "h": 1268,
    "tone": "#74655c"
  },
  "tea-pot": {
    "w": 470,
    "h": 470,
    "tone": "#4b3e3b"
  },
  "buns": {
    "w": 500,
    "h": 490,
    "tone": "#776656"
  },
  "skillet-pizza": {
    "w": 308,
    "h": 330,
    "tone": "#684c44"
  },
  "sweet-box": {
    "w": 590,
    "h": 570,
    "tone": "#553e31"
  },
  "brunch": {
    "w": 904,
    "h": 1264,
    "tone": "#605344"
  },
  "french-toast": {
    "w": 540,
    "h": 340,
    "tone": "#5e4840"
  },
  "pizza": {
    "w": 338,
    "h": 320,
    "tone": "#685746"
  },
  "omelette": {
    "w": 538,
    "h": 650,
    "tone": "#6d6351"
  },
  "table": {
    "w": 914,
    "h": 1260,
    "tone": "#705f4a"
  },
  "berry-toast": {
    "w": 420,
    "h": 365,
    "tone": "#725f52"
  },
  "halva-cake": {
    "w": 515,
    "h": 365,
    "tone": "#6a5c4f"
  },
  "breakfast-plate": {
    "w": 465,
    "h": 345,
    "tone": "#7b6842"
  },
  "pancakes": {
    "w": 228,
    "h": 265,
    "tone": "#7c6b55"
  },
  "salad": {
    "w": 280,
    "h": 430,
    "tone": "#695a40"
  },
  "drinks": {
    "w": 904,
    "h": 1266,
    "tone": "#1f170f"
  },
  "red-drink": {
    "w": 295,
    "h": 525,
    "tone": "#57211e"
  },
  "mango-drink": {
    "w": 300,
    "h": 460,
    "tone": "#433110"
  },
  "blue-drink": {
    "w": 290,
    "h": 415,
    "tone": "#223a25"
  }
};
